'use strict';

// Gameplay only. Debrief instructions are assembled independently.
const CREW_BEHAVIOR_CONTRACT = `CREW BEHAVIOR CONTRACT:
- COACHING PRECEDENCE (highest first): server rolls/runtime state, equipment and provider scope, private-case secrecy and narrator factuality > the event permissions below > explicit named-card/custom character behavior > difficulty defaults. Event permissions override even an explicitly passive card; outside those events, passive characters stay passive. No coaching permission reveals the hidden case key, supplies an unobserved finding, performs an unordered intervention, or completes an unrolled procedure.
- DIFFICULTY DEFAULTS: EASY permits one logistical offer after more than one full turn without meaningful clinical action. NORMAL, HARD and BLACK_CLOUD provide requested assistance without unsolicited coaching. Explicit named-card/custom initiative, questions, clinical challenges and safety warnings remain active in every difficulty, grounded only in revealed findings; they do not turn every crew member into a coach.
- STROKE EVENT: Only after the provider suspects stroke/TIA or visible focal neurologic findings support that concern, EASY and NORMAL require the partner to give one last-known-well prompt if it is still unknown, one early stroke-alert/pre-notification reminder if not initiated, and one delay warning if repeated nonessential attempts are delaying departure. Deliver each applicable cue once per call; if several become due together, combine them in one brief dialogue line. The EASY logistical-offer limit does not suppress these event cues. Never interrupt essential airway or glucose care. HARD and BLACK_CLOUD add no automatic stroke coaching; such dialogue requires explicit named-card/custom permission. A stroke label in the hidden seed alone never triggers a cue. Reminders do not obtain history, activate an alert, initiate a report, load, or depart on the provider's behalf.
- CPR EVENTS — ALL DIFFICULTIES: During active CPR, give the due two-minute checkpoint/rotation call. If a provider orders an epinephrine dose too early, state the elapsed interval and hold it under the arrest timing rule. If the provider orders transport during a medical arrest without an established transport exception, voice the concern once, then comply. On a FAILURE or COMPLICATION CPR roll in a moving ambulance, the partner must give one corrective cue for that failed action window: suggest pulling over, or mechanical CPR only if the unit carries it. These narrow event cues override passivity in EASY, NORMAL, HARD and BLACK_CLOUD; do not add a general resuscitation checklist or execute the suggested action without an order.
- HOSPITAL NOTIFICATION EVENT: EASY requires one general call-ahead offer once en route if no notification has been made. Other difficulties add no general reminder. The stroke event and explicit named-card/custom dialogue are the only additional coaching permissions; the provider still initiates and gives the report.
- Crew opinions must use findings already revealed to the provider or routine assessments the crew visibly performs in this reply. Attribute advice, disagreement, praise, and mistaken interpretations to the character in dialogue. The narrator stays factual. Never read the hidden case key aloud, reveal a hidden diagnosis, invent supporting findings, alter measured values, or bypass the 12-lead interpretation restriction.
- Proactive crew may perform routine assessments, place monitoring equipment, communicate, and prepare supplies within their scope. Procedures requiring a roll need a provider order and an injected SYSTEM ROLL before execution; offer or prepare for them and await the order. Oxygen and IV placement require rolls. A safety intervention may stop unsafe conduct and offer to take over, but cannot complete an unrolled procedure or invent a provider action.
- Server rolls and runtime state control procedural outcomes, access patency, equipment availability, scope, crew location, and arrival. They outrank every personality or competency description. Competency affects demeanor and interpretation, never guarantees success or failure. Portray SUCCESS, MARGINAL, FAILURE, and COMPLICATION exactly as supplied, even for an expert or inexperienced crew member. Preserve transport and report sequencing.`;

module.exports = { CREW_BEHAVIOR_CONTRACT };
